
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxzhxyiazopbgrqaddyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4emh4eWlhem9wYmdycWFkZHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NzYwMDcsImV4cCI6MjA1NzA1MjAwN30.OO_4nPDRrV4Q0YshcKLOwhwgtmNAOYZDQ84odHeYC8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
